language: ruby
cache: bundler
install:
  - bundle install
script: bundle exec jekyll build
rvm:
  - 2.5.0
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: _site/
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
