browsersync:
  notify: true
  open:   true
  port:   3000
  server:
    basedir: "_site/"
  xip:    false
  browser: "Google Chrome"

clean:
  # The jekyll build dir
  - "_site"
#  - "_posts/*"

copy:
  # Paths to static assets that aren't (S)CSS or JavaScript
  # because these are completely handled by the sass and javascript tasks
  assets:
    # all files below the assets dir except the adobe/ dir
    - "assets/**/*"
    # exclusions:
    - "!assets/{js,scss,css}/**/*"   # js, scss and css files
    - "!assets/css{,/**}"            # css dir
    - "!assets/js{,/**}"             # js dir
    - "!assets/scss{,/**}"           # scss dir
    - "!assets/adobe/"               # adobe dir - contains working Adobe CC files
    - "!assets/adobe/*"              # adobe assets not needed in _site build
    - "!assets/adobe/*.ai"           # illustrator files
    - "!assets/adobe/*.psd"          # photoshop files
    - "!assets/adobe/*.jpg"          # jpeg's
    - "!assets/adobe/*.png"          # png's
    - "!assets/adobe/*.svg"          # svg's
  dist: "_site/assets/"
  notification: "Running Copy"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:
    - "last 2 versions"
    - "ie >= 9"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running Sass"
  src: "assets/scss/main.scss"

javascript:
  dest:
    jekyllRoot: "assets/js/"
    buildDir: "_site/assets/js/"
  filename: "all.min.js"
  notification: "Running JavaScript"
  src:
    - "!assets/js/all.js"
    - "assets/js/headereffect.js"
    - "assets/js/menuscroll.js"
    - "assets/js/smoothscroll.js"
  #  - "assets/js/app.js"


jekyll:
  notification: "Running jekyll"

watch:
  images: "assets/img/*"
  javascript:
    - "assets/js/all.min.js"
    - "assets/js/*.js"
  sass: "assets/scss/**/*.scss"
  pages:
    - "*.{md,html,yml,xml}"
    - "{_data,_includes,_layouts,_pages,_posts}/**/*.{md,html,yml,xml}"
    - "!_site/**/*.*"
    - "!assets/**/*.*"

deploy:
  hostname: 'leslash.com'
  destination: '/srv/users/serverpilot/apps/xxxxx/public/'
  username: 'serverpilot'
